### ISSUE TITLE
Recipe issue:  openldap>2.5.0

### ISSUE THREAD

**Issue by bkreider** [conda-forge/python-ldap-feedstock#10]
I'm creating my own recipe for python-ldap and i found that the latest openldap major series 2.5.x removed libldap_r by merging it into libldap.  

The build requirements for openldap need to be restrained to be under 2.5.0.  I'm not sure what that means for the run-time requirement, but I would assume that python-ldap will fail the first time it tries to use libldap_r functions and it cannot find the library.   

Conda-forge hasn't updated openldap to 2.5.x, but once that happens I think there will be problems installing python-ldap.  This would probably mean you need to hotfix the older builds of python-ldap with that upper version constraint or delete and rebuild the old builds.  

Cheers!

**Comment by marcelotrevisani** [comment]
fixed in the latest build
